language: rust
rust: stable
dist: xenial
env:
  global:
    - RUST_BACKTRACE: full
matrix:
  include:
    - os: osx
      env: TARGET=x86_64-apple-darwin
    - os: linux
      env: TARGET=x86_64-unknown-linux-gnu
before_script:
  - rustc -V
  - cargo -V
  - git --version
  - echo $TRAVIS_BRANCH
  - git rev-parse HEAD
notifications:
  email:
    on_success: never
    on_failure: change
before_deploy:
  - export PKG_CONFIG_ALLOW_CROSS=1
  - cargo build --target $TARGET --release
  - mkdir "ruget-${TRAVIS_TAG}-${TARGET}"
  - cp target/$TARGET/release/ruget LICENSE README.md "ruget-${TRAVIS_TAG}-${TARGET}"
  - zip "ruget-${TRAVIS_TAG}-${TARGET}.zip" -r "ruget-${TRAVIS_TAG}-${TARGET}"
deploy:
  provider: releases
  api_key:
    secure: hEZfH+haeO9wHZJuTZl5G+XqEJ2Kr3NTQHu7jRWdHntvCcI++kzoobpoFFlq43g1dIyipJ2xTAVxZxRhh0rX63OlT9TvSVEmPgGOsqLJtr4J5xs286QxW0ON1SiI7kAo61PyAAatmQPKZdK0S/F49Y14Z7Z7/W/h6U44STxVsu1ddmLVkYxi7/OrnozKlg9x3WK5lAgbM5BZwcquCsMh3dJZjN62/ZpVfagymmYkDP9igCod9M+895lFY77BnN7PgufAQfozXHfPJFa1APMOTGFblFlfeJVhu2ik4p4LtmUfebNX57wVD1Q31xfGQhzciRkk3VM9imJS9hr2BBh8DZAZXEpaYloBal+ozG2VxmpLNUWDvmaCdkB2RMjUDaVYd0VMox04b39XaEgYv0Fv3V7tGmoplce9yK0hF42TBbAiHFvxgfz4AiXqDyslXQOvLtt2K0xnxaifGt58TcSavhoAAAq4po7td1i09Q6uK/HEJcBIoG0sS0B2YPb5+ehd2jld11m70s8QvQn0uRbmXlcFvUNFl+QeGPD9funQ/d6wWNNE1xSU8DVe2jZd4js3AtAkc6/hK0fHiXpfTZS+RbLJEnZJ4kPwDg3NnWr1DQd6/P33PEURcdaS99kIweBYJAw0oYXIK1hZXd2ehxPn5OmetmsKjl+OxKoPIsqb8s0=
  file: ruget-${TRAVIS_TAG}-${TARGET}.zip
  skip_cleanup: true
  on:
    repo: KeisukeToyota/ruget
    tags: true
cache: cargo
